---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: basic
spec:
  template:
    metadata:
      labels:
        type: basic
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: basic
      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values:
            - "c"
            - "m"
            - "r"
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values:
            - "4"
            - "8"
            - "16"
            - "32"
        - key: "topology.kubernetes.io/zone"
          operator: In
          values:
            - "us-east-1a"
            - "us-east-1b"
        - key: "kubernetes.io/arch"
          operator: In
          values:
            - "arm64"
  limits:
    cpu: "1000"
    memory: 1000Gi
