# Prometheus Alert Rules for Kubernetes Cluster
# Apply with: kubectl apply -f cluster-alerts.yaml

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-lab-cluster-alerts
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: prometheus
spec:
  groups:
    # =========================================================================
    # Node Alerts
    # =========================================================================
    - name: kubernetes-lab.node
      rules:
        - alert: NodeNotReady
          expr: kube_node_status_condition{condition="Ready",status="true"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Node {{ $labels.node }} is not ready"
            description: "Node {{ $labels.node }} has been not ready for more than 5 minutes."
            runbook_url: "https://docs.example.com/runbooks/node-not-ready"

        - alert: NodeHighCPU
          expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage on {{ $labels.instance }}"
            description: "CPU usage is above 80% for more than 10 minutes on {{ $labels.instance }}. Current value: {{ $value }}%"

        - alert: NodeHighMemory
          expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage on {{ $labels.instance }}"
            description: "Memory usage is above 85% for more than 10 minutes on {{ $labels.instance }}. Current value: {{ $value }}%"

        - alert: NodeDiskPressure
          expr: kube_node_status_condition{condition="DiskPressure",status="true"} == 1
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Disk pressure on {{ $labels.node }}"
            description: "Node {{ $labels.node }} is under disk pressure."

        - alert: NodeMemoryPressure
          expr: kube_node_status_condition{condition="MemoryPressure",status="true"} == 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Memory pressure on {{ $labels.node }}"
            description: "Node {{ $labels.node }} is under memory pressure."

    # =========================================================================
    # Pod Alerts
    # =========================================================================
    - name: kubernetes-lab.pod
      rules:
        - alert: PodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[15m]) * 60 * 15 > 3
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Pod crash looping in {{ $labels.namespace }}/{{ $labels.pod }}"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping with {{ $value }} restarts in the last 15 minutes."

        - alert: PodNotRunning
          expr: kube_pod_status_phase{phase=~"Failed|Pending|Unknown"} > 0
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is not running"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in {{ $labels.phase }} state for more than 15 minutes."

        - alert: ContainerOOMKilled
          expr: kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} > 0
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "Container OOM killed in {{ $labels.namespace }}/{{ $labels.pod }}"
            description: "Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} was OOM killed."

        - alert: PodHighCPU
          expr: sum(rate(container_cpu_usage_seconds_total{container!="POD",container!=""}[5m])) by (namespace, pod) / sum(kube_pod_container_resource_limits{resource="cpu"}) by (namespace, pod) > 0.9
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage in pod {{ $labels.namespace }}/{{ $labels.pod }}"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is using more than 90% of its CPU limit."

    # =========================================================================
    # Deployment Alerts
    # =========================================================================
    - name: kubernetes-lab.deployment
      rules:
        - alert: DeploymentReplicasMismatch
          expr: kube_deployment_spec_replicas != kube_deployment_status_replicas_available
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Deployment {{ $labels.namespace }}/{{ $labels.deployment }} replicas mismatch"
            description: "Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not matched the expected replicas for 10 minutes. Expected: {{ $labels.replicas }}"

        - alert: DeploymentNoReplicas
          expr: kube_deployment_status_replicas_available == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has no replicas"
            description: "Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has had 0 available replicas for more than 5 minutes."

    # =========================================================================
    # PVC Alerts
    # =========================================================================
    - name: kubernetes-lab.storage
      rules:
        - alert: PVCPending
          expr: kube_persistentvolumeclaim_status_phase{phase="Pending"} == 1
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} pending"
            description: "PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} has been pending for more than 15 minutes."

        - alert: PVCHighUsage
          expr: kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes > 0.85
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "PVC {{ $labels.persistentvolumeclaim }} usage above 85%"
            description: "PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is using more than 85% of its capacity. Current usage: {{ $value | humanizePercentage }}"
