apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
  - .
startKIND: false
skipClusterDelete: true
---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
index: 0
commands:
  - command: kubectl apply -f manifests/
---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 180
commands:
  - command: kubectl wait --for=condition=Available deployment/web -n scenario-alb --timeout=60s
  - command: |
      # Wait for ALB to be provisioned (check for ADDRESS)
      for i in $(seq 1 60); do
        ADDR=$(kubectl get ingress web -n scenario-alb -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null)
        [ -n "$ADDR" ] && exit 0
        sleep 3
      done
      exit 1
