apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
  - .
startKIND: false
skipClusterDelete: true
---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
index: 0
commands:
  - command: kubectl apply -f manifests/
---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 120
commands:
  - command: |
      DESIRED=$(kubectl get ds fluentd -n scenario-daemonset -o jsonpath='{.status.desiredNumberScheduled}')
      READY=$(kubectl get ds fluentd -n scenario-daemonset -o jsonpath='{.status.numberReady}')
      [ "$READY" -ge 1 ] && [ "$READY" -eq "$DESIRED" ]
