---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-nlb
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
