---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
  - apiGroups:  # Use "" for core API group
      - ""
    resources:
      - "nodes"
    verbs:
      - "get"
      - "list"
      - "watch"
