apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
  - .
startKIND: false
skipClusterDelete: true
---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
index: 0
commands:
  - command: kubectl apply -f manifests/
---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 90
commands:
  - command: kubectl wait --for=condition=Available deployment/web -n scenario-pdb --timeout=60s
  - command: kubectl get pdb web -n scenario-pdb
