apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
  - .
startKIND: false
skipClusterDelete: true
---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
index: 0
commands:
  - command: kubectl apply -f manifests/
---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 60
commands:
  - command: kubectl wait --for=condition=Ready pod/app -n scenario-secret --timeout=60s
  - command: kubectl logs app -n scenario-secret | grep DB_USER
