apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
  - .
startKIND: false
skipClusterDelete: true
---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
index: 0
commands:
  - command: kubectl apply -f manifests/
---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 60
commands:
  - command: kubectl wait --for=condition=Available deployment/api -n scenario-cilium-l7 --timeout=60s
  - command: kubectl get ciliumnetworkpolicy api-l7-policy -n scenario-cilium-l7
