apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
  - .
startKIND: false
skipClusterDelete: true
---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
index: 0
commands:
  - command: kubectl apply -f manifests/
---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 60
commands:
  - command: kubectl wait --for=condition=Available deployment/web -n scenario-nodeport --timeout=60s
  - command: |
      PORT=$(kubectl get svc web -n scenario-nodeport -o jsonpath='{.spec.ports[0].nodePort}')
      [ "$PORT" -eq 30080 ]
